id: P14F222EF
initial_creation_type: input
source_metadata:
  title: Prajñāpāramitāhṛdayasūtra
  language: bo
  volumes:
    c900dd32b8dd47c5a6b3245929afc70a:
      title: Complete text
      base_file: Complete text.txt
      work_id: W4649E442
  chapter_to_tile: {}
created_at: '2022-03-02T09:00:12.292782'
last_modified_at: '2022-03-02T09:00:12.292795'
